version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: statbasket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # --- ДОБАВЛЕНА ЭТА СТРОКА ---
      # Она кладет ваш файл init.sql в специальную папку внутри контейнера.
      # PostgreSQL автоматически выполнит всё из этой папки при самом первом запуске!
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/statbasket_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secretpassword123
      # --- ИЗМЕНЕНА ЭТА СТРОКА ---
      # Меняем update на none, так как базу нам создаст наш файл init.sql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - db

volumes:
  pgdata: