spring.application.name=statbasket-server

spring.datasource.url=jdbc:postgresql://localhost:5433/StatBasket

spring.datasource.username=Roman
spring.datasource.password=123

# ????????? Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.fail-on-empty-beans=false